---
name: grid-simulator-dev
channels:
  - conda-forge
dependencies:
  - python=3.12
  - bandit=1.8
  - black=25.1
  - cachecontrol-with-filecache=0.14
  - mypy=1.16
  - pip-audit=2.9
  - pytest=8.4
  - pytest-asyncio=1.0
  - pytest-cov=6.1
  - pytest-mock=3.14
  - twine=6.2
  - pip=25.3
  - pip:
    - build~=1.3.0
